package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.sql.DataSource;

import model.UserBean;
import utils.Utils;

public class UserDao {
	
	private DataSource dataSource;
	private Connection conn;
	private PreparedStatement pstmt;
	private ResultSet rs;
	
	public UserDao(DataSource dataSource) {
		this.dataSource = dataSource;
	}

	public boolean validate(UserBean user) { 

		boolean status = false;
		
		String INSERT_USER_SQL = "INSERT INTO customer(id, password, name, email, phone, address) "
				+ "VALUES (?, ?, ?, ?, ?, ?);";
		
		try {
			conn = dataSource.getConnection();
			pstmt = conn.prepareStatement(INSERT_USER_SQL);

			pstmt.setString(1, user.getId());
			pstmt.setString(2, user.getPassword());
			pstmt.setString(3, user.getName());
			pstmt.setString(4, user.getEmail());
			pstmt.setString(5, user.getPhone());
			pstmt.setString(6, user.getAddress());

			result = pstmt.executeUpdate();

		} catch (SQLException e) {
			System.out.println("SQL 에러");
		}

		return result;
	}

}
